# Generated by Django 5.0.6 on 2025-04-18 15:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('physio_name', models.CharField(max_length=30, null=True)),
                ('contact_number', models.CharField(max_length=20, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True)),
                ('specialization', models.CharField(max_length=30, null=True)),
                ('booking_date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('status', models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Pending', 'Pending')], max_length=30, null=True)),
                ('appointment_date', models.DateField(null=True)),
                ('consulting_type', models.CharField(choices=[('Home Visit', 'Home Visit'), ('Clinic Visit', 'Clinic Visit')], max_length=30, null=True)),
                ('selected_slot', models.CharField(max_length=100, null=True)),
                ('is_emergency', models.IntegerField(null=True)),
                ('appartment', models.CharField(max_length=50, null=True)),
                ('landmark', models.CharField(max_length=30, null=True)),
                ('area', models.CharField(max_length=30, null=True)),
                ('city', models.CharField(max_length=30, null=True)),
                ('pincode', models.IntegerField(null=True)),
                ('patient_name', models.CharField(max_length=30, null=True)),
                ('patient_contactno', models.CharField(max_length=20, null=True)),
                ('patient_email', models.EmailField(max_length=254, null=True)),
                ('patient_gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True)),
                ('rejection_reason', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'appointments',
            },
        ),
    ]
