# Generated by Django 5.0.6 on 2025-04-18 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Physiotherapist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, null=True)),
                ('username', models.CharField(max_length=20, null=True)),
                ('password', models.CharField(max_length=15, null=True)),
                ('contact_no', models.CharField(max_length=15, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=30, null=True)),
                ('photo', models.ImageField(default='default.jpg', upload_to='physio_photos/')),
                ('appartment', models.CharField(max_length=20, null=True)),
                ('landmark', models.CharField(max_length=20, null=True)),
                ('area', models.CharField(max_length=20, null=True)),
                ('city', models.CharField(max_length=20, null=True)),
                ('pincode', models.IntegerField(null=True)),
                ('clinic_start_time', models.TimeField(null=True)),
                ('clinic_end_time', models.TimeField(null=True)),
                ('qualification', models.CharField(max_length=50, null=True)),
                ('qualification_photo', models.ImageField(default='default.jpg', upload_to='qualification_photos/')),
                ('specialization', models.CharField(max_length=50, null=True)),
                ('experience', models.IntegerField(null=True)),
                ('rating', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3, help_text='Rating from 1 to 5', null=True)),
                ('feedback', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
