# Generated by Django 5.0.6 on 2025-04-18 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='physiotherapist',
            name='feedback',
        ),
        migrations.RemoveField(
            model_name='physiotherapist',
            name='rating',
        ),
        migrations.AddField(
            model_name='physiotherapist',
            name='average_rating',
            field=models.FloatField(default=0, null=True),
        ),
    ]
