# Generated by Django 5.0.6 on 2025-04-18 17:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingsFeedback',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('physio_name', models.CharField(max_length=200)),
                ('patient_name', models.CharField(max_length=200)),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('feedback', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment_id', models.ForeignKey(db_column='appointment_id', on_delete=django.db.models.deletion.CASCADE, to='appointment.appointment')),
            ],
            options={
                'db_table': 'ratings_feedback',
            },
        ),
    ]
